### ISSUE TITLE
关于前后端合作开发和代码分支管理

### ISSUE THREAD

**Issue by terrykingcha** [IMAXGINEDIGITAL/notjustidea#1]
## 关于分支管理
- `master` 发布分支，每一次merge到master，必会打一个tag，并发布到线上系统。这也就意味着，`master`分支不允许手动提交代码。
- `dev` 可测试分支，在每一个迭代周期内，供前后端联调或测试人员测试。当测试在迭代周期内测试通过，可发布上线时，需暂时冻结`dev`的任何提交和PR。并发起PR到`master`分支，之后完成一次发布动作。
- `system`，后端开发分支。后端的代码都保存在`sys`目录下，结构按后端的习惯自定。后端的所有开发提交都**push**到`system`分支。如在开发阶段需要联调前端代码，可以**merge**最新的`dev`分支。当后端在完成一部分功能，可供前端联调时，发PR到`dev`分支。
- `webpages`，前端开发分支。前端的代码都保存在`webpages`目录下，结构按前端的习惯自定。前端的所有开发提交都**push**到`webpages`分支。如在开发阶段需要联调后端代码，可以**merge**最新的`dev`分支。当前端在完成一部分功能，可供后端联调时，发PR到`dev`分支。
## 关于联调

首先要保证，`dev`分支上，前后端的代码是可供联调的。并且在前后端各自的目录下，用`README`详细说明，如何通过源码搭建服务以供对方进行本地联调。同时，在时间允许的情况下，后端可以用`mocha`等单元测试工具，来辅助提高后端接口的稳定性。进一步，在时间更加允许的情况下，后端代码接入github的[circel ci](https://circleci.com/)系统，并在每次提交代码和发PR到dev时，跑通单元测试。

**Comment by IMAXGINEDIGITAL** [comment]
已整理发布Wiki。
