### ISSUE TITLE
关于注册时用户名和地区的设置

### ISSUE THREAD

**Issue by terrykingcha** [IMAXGINEDIGITAL/notjustidea#5]
因为用户名和地区字段属于用户系统，所以在注册流程中不建议把它放在第一步。可以考虑，在邮箱激活后，进行用户信息的设置。用户可以选择跳过这个步骤。如跳过，用户名默认给予一个全局唯一的ID号，地区默认以IP所在地设置。

**Comment by youmaoxian** [comment]
同意更改。设计修改后给到。
